### ISSUE TITLE
TWI-Interface in AVR

### ISSUE THREAD

**Issue by Saturi92** [igittigitt/ov7670#1]
Nutzen des TWI-Interface in AVR
**To Do:**

- [x] verstehen der Register
- [x] einstellen der Register
- [ ] erstellen von den nötigen Funktionen:

- [ ]        Write-Funktion erstellen
- [ ]        Read-Funktion erstellen

**Comment by igittigitt** [comment]
In english? REALLY?

**Comment by Saturi92** [comment]
Okay, überredet :D 
Da es bisher so wenige deutschsprachige "Anleitungen" zu dem Thema gibt, machen wir es auf deutsch.

**Comment by Saturi92** [comment]
Bei der Erstellung der ersten Write Funktion habe ich mich größtenteils an folgende Anleitung gehalten:
https://www.mikrocontroller.net/articles/AVR_TWI

Soweit kann ich auch alles nachvollziehen, bis auf die Maskierung bei der Fehlerabgfrage.
Das habe ich auch im Code deutlich gemacht.vielleicht kann mir dort jemand zur Seite stehen.
