### ISSUE TITLE
xCLK

### ISSUE THREAD

**Issue by Saturi92** [igittigitt/ov7670#3]
Ich möchte noch einmal den Betrieb der xCLK aufgreifen.
Aktuell stehen wir vor zwei Möglichkeiten

- xCLK per Timer mit 8MHz betreiben
- xCLK per Clock Out mit 16MHz betreiben

Ich würde entgegen Ollis Meinung die 16MHz bevorzugen, weil wir den Kamera Chip dann innerhalb der Spezifikation betreiben. Selbst wenn wir die PCLK nachher deutlich langsamer betreiben, weiß ich nicht inwiefern sich da die xCLK drauf auswirkt.)

Bisher wissen wir nur, dass es mit 8MHz auch geht, aber wir kennen die Zusammenhänge nicht wirklich und ich denke, dass es dann "gefährlich" ist, die unter der Spezifikation zu betreiben.

**Comment by igittigitt** [comment]
Wir können gern mit gebrückten  Prozessortakt beginnen. Später, wenn alles mal stabil läuft können wir ja mal sehen wie weit man die Specs „dehnen“ kann ;-)
