### ISSUE TITLE
Übertragungsprotokoll

### ISSUE THREAD

**Issue by Saturi92** [igittigitt/ov7670#5]
Das Übertragungsprotokoll für den Bildtransfer muss für die verschiedenen Farbformate festgelegt werden

- [ ] nur Y
- [ ] YUV
- [ ] RGB

**Comment by igittigitt** [comment]
Wie im Forum schon besprochen sollten wir YUV nehmen, weil es am effektivsten ist. Dabei werden zwei Pixel in drei Byte übermittelt. Wir nehmen nur den Y (Luminanz) Anteil.

Deine Umfrage ist dahingehend falsch, weil es keinen reinen Y Modus gibt. Das muss man selbst machen, durch ausmaskieren der Bits.

P.S. Wir sollteb in den Docs oder im Wiki ein paar Grundlagen und Links zu den Farbsystemen hinterlegen, sowie die Datenübertragung und Umrechnungsformeln. Das werden wir noch brauchen.

**Comment by Saturi92** [comment]
Hallo Olli, das hast du falsch verstanden :)
Das ist keine Umfrage sondern eine Check-Liste.
nur für die Übertragung zum PC brauchen wir eben ein Übertragungsprotokoll dass Beispielsweise auch Bildanfang, Zeilen Anfang etc. Signalisiert.
Und da wir später vielleicht auch ins farbige gehen wollen brauchen wir dann jeweils unterschiedliche Protokolle.
Da wir zunächst nur die Y-Stufe übertragen wollen, brauchen wir ein Übertragungsprotokoll dafür. (deshalb steht das auch oben)
