### ISSUE TITLE
Auflösung von VGA -> QVGA im Terminal umstellen

### ISSUE THREAD

**Issue by igel1** [igittigitt/ov7670#6]
### Bugbeschreibung:   

OV7670-Terminal versetzt OV7670 in VGA-Auflösung und erhält beim anschließenden Versuch, VGA-Bilder darzustellen nur Teilbilder aus dem FiFo.

### Lösungsansatz:

- [x] Umstellung auf QVGA
- [x] Umstellung auf RGB565

### Hintergründe:  

640x480 a 2 Byte/Pixel passen nicht in den AL422B-FiFo.
Die Umstellung ist vermutlich ein Klacks für David und erleichtert Michael und Andreas die  weitere Fehlersuche.  Natürlich sollten dann in einem Abwasch auch in allen Initialisierungsroutinen, welche das Bildformat in Richtung AVR schicken, umgestellt werden.

### Quellen:

Bugmeldung von Michael U. vom 08.03.2019 09:09
[https://www.mikrocontroller.net/topic/444953?goto=5763812#5763112](url)

Weitere Notizen zum Bugfixing von Igel1 vom 08.03.2019 19:23
[https://www.mikrocontroller.net/topic/444953?goto=5763812#5763812](url)

**Comment by Saturi92** [comment]
Implementierung ist im Gange:
Bei der Initialisierung wird Register 0x12 auf den Wert 0x16 gesetzt.

Als Farbformat wird RGB565 gewählt
